In [ ]:
# Question 1  : Numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). 
# The numbers obtained should be printed in a list
numb = []
for i in range (2000,3201):
    if i % 7 == 0 and i %5 != 0 :
        numb.append(i)
print(numb)

In [ ]:
# Question 2 :  Write a program that can compute the factorial of a given number.
n = int (input("Put number her : "))
def fact (numb):
    if numb == 0:
        return 1
    return numb * fact(numb-1)
f = fact (n)
print("The factorial of",n ,"is",f)

In [23]:
# Question 3 :  With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that 
# is an integral number between 1 and n (both included). Then, the program should print the dictionary
def gen(n):
    return {i: i*i for i in range(1, n+1)}
nmb = int(input("Enter an integer number: "))
print(gen(nmb))

Enter an integer number: 5
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [22]:
# Question 4 : Given a non-empty string and an integral n, return a new string where the char at index n has been removed. 
# The value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1 inclusive).

word = str(input("enter a word :"))
n = int(input("enter a number :"))
l = []
# if the user put number bigger than len of  word
if n > len(word):
    print("the number must be smaller than",len(word))
# function remove 
def rem (word,n):
    return word[:n]+ word[n+1:]
rem(word,n)

enter a word :kitten
enter a number :1


'ktten'

In [20]:
# Question 5 : Write a NumPy program to convert a NumPy array into a Python list structure

import numpy as np

n = np.array([[0,1,2],[3,4,5],[6,7,8]])
print("Numpy array :")
print(n)

# conver from numpy array to a list
l = n.tolist()
print("New list :")
print(l)

Numpy array :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
New list :
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [4]:
# Question 6 : Write a NumPy program to compute the covariance matrix of two given arrays.

import numpy as np
array_1 = np.array([0,1,2]) 
array_2 = np.array([2,1,0])
cov = np.cov(array_1,array_2)
print(cov)


[[ 1. -1.]
 [-1.  1.]]


In [21]:
# Question 7 : Write a program that calculates and prints the value according to the given formula:
# Q= Square root of [(2 * C * D)/H] The following are the fixed values of C and H: C is 50. H is 30. 

from math import sqrt
D=input('Enter a list of number:')
liste=D.split()
D = liste

C=50
H=30
def formule (C,D,H):
    return sqrt((2*C*int(D))//H)
def cal(D,C,H) :
    for i in range (0,len(D)):
        print (int((formule(C,D[i],H))))
cal(D,C,H)


Enter a list of number:100 150 180
18
22
24
